[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOW-FROM https://image-analyzer.streamlit.app/"
    Content-Security-Policy = "frame-ancestors 'self' https://image-analyzer.streamlit.app/"
