[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = '''
    default-src 'self';
    script-src 'self';
    img-src 'self' https://*.cdn.com;
    frame-ancestors 'self' https://*.streamlit.app;
    '''
